name: CI - Lint & Prettier

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main # 👈 chạy CI khi push thẳng vào main
      - chore/**
      - feat/**
      - fix/**
  workflow_dispatch: {} # 👈 cho phép Run workflow thủ công trong tab Actions

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies (clean)
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          # generate chỉ cần biến môi trường hợp lệ, không cần DB thật
          DATABASE_URL: postgresql://user:pass@localhost:5432/db

      - name: Prettier check
        run: npx prettier --check .

      - name: ESLint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint-and-format
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # placeholder để Next/Auth không báo khi build
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: dummysecretfordevonly
      DATABASE_URL: postgresql://user:pass@localhost:5432/db
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies (clean)
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Next.js build
        run: npm run build
